### ISSUE TITLE
Availablity on Amazon store

### ISSUE THREAD

**Issue by dasbiswajit** [nextcloud/Android-SingleSignOn#525] opened 2023-02-22 16:08 UTC
Hello Guy's,

As you know Nextcloud bookmarks is present on Amazon store it is fully integrated with SSO. Currently Amazon is not allowing to publish as the sso version of the APP. As they are expecting the sign-in should not direct anywhere except Amazon store. Can revert back to both the options however have refactored the application a lot to support SSO. I have been speaking with @tobiasKaminsky to publish the app in amazon store do you think we can modify the message to redirect to amazon store?

App Name : Nextcloud Bookmarks
App Version/Package Name : 1.19

Issue Description: App displays error message
Steps to reproduce issue:
1. Install and launch the app
2. Tap on "NEXTCLOUD SINGLE SIGN ON (SSO)" button
3. Tap on the link provided

Actual result : Observed that app displays error message and on tapping the link provided app is redirecting to Google play store.
Expected result : App should not display error messages and should work as intended .

Affected device list:Fire HD 6 (2014), Fire HD 7 (2014), Fire HDX 8.9 WAN (2014), Fire HDX 8.9 (2014), Fire HD 10 (2015), Fire HD 8 (2015), Fire (2015), Fire HD 8 (2016), Fire HD 8 (2017), Fire 7 (2017), Fire HD 10 (2017), Fire HD 8 (2018),  Fire HD 10 (2019), Fire HD 8 (2020), Fire 7 (2019), Fire HD 10 (2021), Fire HD 10 Plus (2021), Fire 7 (12th Generation), Fire HD 8 (2022), Fire HD 8 Plus (2022)

NOTE : Amazon devices do not support third party app stores

**Comment by stefan-niedermann** [comment] 2023-02-22 16:31
Duplicate of https://github.com/nextcloud/Android-SingleSignOn/issues/305#issuecomment-776549823

**Closed by stefan-niedermann** 2023-02-22 16:31 UTC
